### ISSUE TITLE
JSON syntax error on DIDDocument deserialization

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.DID.JS.SDK#102]
Multiple tests are failing with an Invalid JSON syntax when trying to deserialize a DIDDocument. We can run tests from verifiablecredential.test; 'testSelfProclaimedCredentialFromCid' and 'testSelfProclaimedCredential'.

Here are the output of these two tests.

```
let Tests › testSelfProclaimedCredential
  Invalid JSON syntax (DIDDocument): {
      "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
      "publicKey" : [ {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#key2",
        "type" : "ECDSAsecp256r1",
        "controller" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
        "publicKeyBase58" : "dRf1jbyPoUarVvsJrWWp5fgGdM7uPRWkLrrjtGtUHgJD"
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#key3",
        "type" : "ECDSAsecp256r1",
        "controller" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
        "publicKeyBase58" : "vs5iJcaMJkgHvB3YVMDXUc39ihDeVxWX8UVYXHdcZTvs"
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#primary",
        "type" : "ECDSAsecp256r1",
        "controller" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
        "publicKeyBase58" : "vMYSz32qbWsNeDJpKsuuMaFsiApuZMz9XVy9DmEwysWg"
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#recovery",
        "type" : "ECDSAsecp256r1",
        "controller" : "did:elastos:iXDjXMyy9GyRnXGve71aKKJVW6kYtiWBmb",
        "publicKeyBase58" : "23AVdLG9CmpGvwFDC4js9RUBWsfugjM2RwfsDvdJCkPou"
      } ],
      "authentication" : [ "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#key2", "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#key3", "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#primary" ],
      "authorization" : [ "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#recovery" ],
      "verifiableCredential" : [ {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#email",
        "type" : [ "BasicProfileCredential", "EmailCredential", "InternetAccountCredential" ],
        "issuer" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj",
        "issuanceDate" : "2021-03-19T08:41:55Z",
        "expirationDate" : "2026-03-19T08:41:55Z",
        "credentialSubject" : {
          "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
          "email" : "john@example.com"
        },
        "proof" : {
          "type" : "ECDSAsecp256r1",
          "created" : "2021-03-19T08:41:55Z",
          "verificationMethod" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#primary",
          "signature" : "9cqDHbdoK7DOEH87f1vE34BsAmPxFkFAuQ7aPt5W5pjViE6jY51S2kPr7Yf59O8RZj9JqFjVU7_pr9uqXfXpVw"
        }
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#profile",
        "type" : [ "BasicProfileCredential", "SelfProclaimedCredential" ],
        "issuer" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
        "issuanceDate" : "2021-03-19T08:41:55Z",
        "expirationDate" : "2026-03-19T08:41:55Z",
        "credentialSubject" : {
          "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y",
          "email" : "john@example.com",
          "gender" : "Male",
          "language" : "English",
          "name" : "John",
          "nation" : "Singapore",
          "twitter" : "@john"
        },
        "proof" : {
          "type" : "ECDSAsecp256r1",
          "created" : "2021-03-19T08:41:55Z",
          "verificationMethod" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#primary",
          "signature" : "exv5EWlZLr7FL27k95Ynq-b8ac0PjNZZ_cC5t2dm0O9eMPyWqcPMQgMxbX-tbKtTXsukwTHbtHYMOgDHZM-mrA"
        }
      } ],
      "service" : [ {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#carrier",
        "type" : "CarrierAddress",
        "serviceEndpoint" : "carrier://X2tDd1ZTErwnHNot8pTdhp7C7Y9FxMPGD8ppiasUT4UsHH2BpF1d",
        "ABC" : "Helloworld",
        "BAR" : "Foobar",
        "DATE" : "2021-03-19T08:41:55Z",
        "FOO" : 678,
        "FOOBAR" : "Lalala...",
        "MAP" : {
          "ABC" : "Helloworld",
          "BAR" : "Foobar",
          "DATE" : "2021-03-19T08:41:55Z",
          "FOO" : 678,
          "FOOBAR" : "Lalala...",
          "abc" : "helloworld",
          "bar" : "foobar",
          "date" : "2021-03-19T08:41:55Z",
          "foo" : 123,
          "foobar" : "lalala..."
        },
        "abc" : "helloworld",
        "bar" : "foobar",
        "date" : "2021-03-19T08:41:55Z",
        "foo" : 123,
        "foobar" : "lalala...",
        "map" : {
          "ABC" : "Helloworld",
          "BAR" : "Foobar",
          "DATE" : "2021-03-19T08:41:55Z",
          "FOO" : 678,
          "FOOBAR" : "Lalala...",
          "abc" : "helloworld",
          "bar" : "foobar",
          "date" : "2021-03-19T08:41:55Z",
          "foo" : 123,
          "foobar" : "lalala..."
        }
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#openid",
        "type" : "OpenIdConnectVersion1.0Service",
        "serviceEndpoint" : "https://openid.example.com/"
      }, {
        "id" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#vcr",
        "type" : "CredentialRepositoryService",
        "serviceEndpoint" : "https://did.example.com/credentials"
      } ],
      "expires" : "2026-03-19T08:41:55Z",
      "proof" : {
        "type" : "ECDSAsecp256r1",
        "created" : "2021-03-19T08:41:55Z",
        "creator" : "did:elastos:iXcRhYB38gMt1phi5JXJMjeXL2TL8cg58y#primary",
        "signatureValue" : "JaqJSpYq1HfWIfiAOSBHMSZm7B93SU4xLGZCwmWNg7hXLl-5MEkwj8e3TAAjmzAc1SIdIesOili7rQ8L8fnqxg"
      }
    }
    Caused by: Invalid DID

      145 | 			return obj;
      146 | 		} catch (e) {
    > 147 | 			throw new DIDSyntaxException("Invalid JSON syntax" + (Logger.levelIs(Logger.DEBUG) ? (" (" + clazz.name + "): " + source) : ""), e);
          | 			      ^
      148 | 		}
      149 | 	}
      150 |

      at Function.<anonymous> (../../src/didentity.ts:147:10)
      at ../../node_modules/tslib/tslib.es6.js:76:71
      at __awaiter (../../node_modules/tslib/tslib.es6.js:72:12)
      at Function.parse (../../dist/did.js:467:16)
      at Function.parseContent (../../src/diddocument.ts:1980:30)
      at CompatibleData.getDocument (utils/testdata.ts:227:31)
      at Object.<anonymous> (verifiablecredential.test.ts:82:26)
```
```
let Tests › testSelfProclaimedCredentialFromCid

    Invalid JSON syntax (DIDDocument): {
      "id" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj",
      "publicKey" : [ {
        "id" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#primary",
        "type" : "ECDSAsecp256r1",
        "controller" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj",
        "publicKeyBase58" : "238wLrC5sAn2qDhp78ZodB2ywfQ3g7zmaPRidgARStHGL"
      } ],
      "authentication" : [ "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#primary" ],
      "verifiableCredential" : [ {
        "id" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#profile",
        "type" : [ "BasicProfileCredential", "SelfProclaimedCredential" ],
        "issuer" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj",
        "issuanceDate" : "2021-03-19T08:41:55Z",
        "expirationDate" : "2026-03-19T08:41:55Z",
        "credentialSubject" : {
          "id" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj",
          "email" : "issuer@example.com",
          "language" : "English",
          "name" : "Test Issuer",
          "nation" : "Singapore"
        },
        "proof" : {
          "type" : "ECDSAsecp256r1",
          "created" : "2021-03-19T08:41:55Z",
          "verificationMethod" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#primary",
          "signature" : "koAuJbp66eMjACIXvHGp-qFDTIG7I4i6rB9RRV4RHCBl2YAPrXN7zBse46VKwuDZpum41gRE3WmUvRS22_ZOrw"
        }
      } ],
      "expires" : "2026-03-19T08:41:55Z",
      "proof" : {
        "type" : "ECDSAsecp256r1",
        "created" : "2021-03-19T08:41:55Z",
        "creator" : "did:elastos:imUUPBfrZ1yZx6nWXe6LNN59VeX2E6PPKj#primary",
        "signatureValue" : "4LPTHhmcEBoSLt3b01nJUs5Pxu4SAlK5y-FSoCAai2DWjlC2LEf_TNOXJbNdPUfTMzhAR8jyWjzIIRkeb6eJ7Q"
      }
    }
    Caused by: Invalid DID

      145 | 			return obj;
      146 | 		} catch (e) {
    > 147 | 			throw new DIDSyntaxException("Invalid JSON syntax" + (Logger.levelIs(Logger.DEBUG) ? (" (" + clazz.name + "): " + source) : ""), e);
          | 			      ^
      148 | 		}
      149 | 	}
      150 |

      at Function.<anonymous> (../../src/didentity.ts:147:10)
      at ../../node_modules/tslib/tslib.es6.js:76:71
      at __awaiter (../../node_modules/tslib/tslib.es6.js:72:12)
      at Function.parse (../../dist/did.js:467:16)
      at Function.parseContent (../../src/diddocument.ts:1980:30)
      at CompatibleData.getDocument (utils/testdata.ts:227:31)
      at CompatibleData.loadAll (utils/testdata.ts:349:14)
      at Object.<anonymous> (verifiablecredential.test.ts:193:15)
```

**Comment by carlduranleau** [comment]
Fixed from other updates
