### ISSUE TITLE
[Tests] Test output only shows logged content at the end with useless line number

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.DID.JS.SDK#35]
When running tests, console logging is only displayed at the end of all tests, and includes useless information as shown here:

`console.log
    2021-05-14T02:58:14.231Z DEBUG FileSystemStorage  Initializing DID store at /home/carlduranleau/git/Elastos.DID.JS.SDK/generated/tmp/DIDStore

      at Logger.debug (../src/logger.ts:18:17)

  console.log
    DID store opened: {}, cache(init:{}, max:{}) /home/carlduranleau/git/Elastos.DID.JS.SDK/generated/tmp/DIDStore 16 128

      at new DIDStore (../src/didstore.ts:86:11)

  console.log
    2021-05-14T02:58:15.653Z DEBUG FileSystemStorage  Initializing DID store at /home/carlduranleau/git/Elastos.DID.JS.SDK/generated/tmp/DIDStore

      at Logger.debug (../src/logger.ts:18:17)
`

Logging should be in sync with the test executions and we should only see the logged payload without any debugging information.

**Comment by carlduranleau** [comment]
Not really an issue for now. We may investigate this later but it's not mandatory.
